### ISSUE TITLE
Restore CTRL-click portrait selection / grouping

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1676]
Lost it during the subviews work, since it worked in 0.8.8.

**Comment by bradallred** [comment]
Remind me what this is supposed to do?

**Comment by lynxlynxlynx** [comment]
Additively select.

**Comment by bradallred** [comment]
that just sounds like shift+click to me. how is it different?

**Comment by lynxlynxlynx** [comment]
The same thing, but neither works. Now that I tried it I see it's probably just another bad lambda problem:
```
[Python/ERROR]: TypeError: PortraitButtonOnShiftPress() missing 1 required positional argument: 'pcID'
```

**Comment by bradallred** [comment]
I just fixed that when I commented :)
