### ISSUE TITLE
 Fail to build on Linux (GCC 11.2)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1498]
#### Bug description
Here is part of the output : 

```
[  3%] Building CXX object gemrb/core/CMakeFiles/gemrb_core.dir/CharAnimations.cpp.o
In file included from /home/elvire/gemrb/gemrb/gemrb/includes/ie_types.h:32,
                 from /home/elvire/gemrb/gemrb/gemrb/includes/globals.h:31,
                 from /home/elvire/gemrb/gemrb/gemrb/core/Audio.h:26,
                 from /home/elvire/gemrb/gemrb/gemrb/core/Audio.cpp:21:
/home/elvire/gemrb/gemrb/gemrb/core/System/String.h: In instantiation of ‘typename std::enable_if<std::is_integral<T>::value, char>::type FixedSizeString<LEN, CMP>::operator[](T) const [with T = int; long unsigned int LEN = 8; int (* CMP)(const char*, const char*, size_t) = strncasecmp; typename std::enable_if<std::is_integral<T>::value, char>::type = char]’:
/home/elvire/gemrb/gemrb/gemrb/core/Resource.h:60:17:   required from here
/home/elvire/gemrb/gemrb/gemrb/core/System/String.h:157:26: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
  157 |                 assert(i < LEN);
      |                        ~~^~~~~
/home/elvire/gemrb/gemrb/gemrb/core/System/String.h:157:23: error: ‘assert’ was not declared in this scope
  157 |                 assert(i < LEN);
      |                 ~~~~~~^~~~~~~~~
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by FrElvire** [comment]
Build is now OK even if there are ton of warning like this one

```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/include/g++-v11/cassert:44,
                 from /home/elvire/gemrb/gemrb/gemrb/core/System/String.h:25,
                 from /home/elvire/gemrb/gemrb/gemrb/includes/ie_types.h:32,
                 from /home/elvire/gemrb/gemrb/gemrb/includes/globals.h:31,
                 from /home/elvire/gemrb/gemrb/gemrb/core/Video/Video.h:30,
                 from /home/elvire/gemrb/gemrb/gemrb/plugins/SDLVideo/SDLVideo.h:24,
                 from /home/elvire/gemrb/gemrb/gemrb/plugins/SDLVideo/SDL20Video.h:24,
                 from /home/elvire/gemrb/gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp:21:
/home/elvire/gemrb/gemrb/gemrb/core/System/String.h: In instantiation of ‘typename std::enable_if<std::is_integral<T>::value, char>::type FixedSizeString<LEN, CMP>::operator[](T) const [with T = int; long unsigned int LEN = 8; int (* CMP)(const char*, const char*, size_t) = strncasecmp; typename std::enable_if<std::is_integral<T>::value, char>::type = char]’:
/home/elvire/gemrb/gemrb/gemrb/core/Resource.h:60:17:   required from here
/home/elvire/gemrb/gemrb/gemrb/core/System/String.h:158:26: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
  158 |                 assert(i < LEN);
      |                        ~~^~~~~
[ 99%] Linking CXX shared module ../SDLVideo.so
```
